2018-07-15 22:39:11,899 ERROR: Exception on / [GET] [in /Users/Fiona/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/Fiona/microblog/app/routes.py", line 22, in index
    if form.validate_on_submit():
TypeError: validate_on_submit() missing 1 required positional argument: 'self'
2018-07-15 22:39:33,456 INFO: Microblog startup [in /Users/Fiona/microblog/app/__init__.py:25]
2018-07-15 22:39:34,815 ERROR: Exception on / [GET] [in /Users/Fiona/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/Fiona/microblog/app/routes.py", line 22, in index
    if form.validate_on_submit():
TypeError: validate_on_submit() missing 1 required positional argument: 'self'
2018-07-15 22:39:44,693 INFO: Microblog startup [in /Users/Fiona/microblog/app/__init__.py:25]
2018-07-15 22:43:10,405 INFO: Microblog startup [in /Users/Fiona/microblog/app/__init__.py:25]
2018-07-15 22:54:26,925 INFO: Microblog startup [in /Users/Fiona/microblog/app/__init__.py:25]
2018-07-15 22:54:28,980 ERROR: Exception on / [GET] [in /Users/Fiona/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/Fiona/microblog/app/routes.py", line 30, in index
    return render_template('index.html', title='Home', form=form, posts=posts)
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/Fiona/microblog/app/templates/index.html", line 5, in template
    {{% if form %}}
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 875, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 620, in parse_tuple
    args.append(parse())
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 432, in parse_expression
    return self.parse_condexpr()
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 437, in parse_condexpr
    expr1 = self.parse_or()
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 450, in parse_or
    left = self.parse_and()
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 459, in parse_and
    left = self.parse_not()
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 470, in parse_not
    return self.parse_compare()
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 474, in parse_compare
    expr = self.parse_math1()
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 496, in parse_math1
    left = self.parse_concat()
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 507, in parse_concat
    args = [self.parse_math2()]
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 517, in parse_math2
    left = self.parse_pow()
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 528, in parse_pow
    left = self.parse_unary()
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 546, in parse_unary
    node = self.parse_primary()
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 583, in parse_primary
    self.fail("unexpected '%s'" % describe_token(token), token.lineno)
  File "/Users/Fiona/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
2018-07-15 22:56:58,054 INFO: Microblog startup [in /Users/Fiona/microblog/app/__init__.py:25]
2018-07-15 23:00:04,570 INFO: Microblog startup [in /Users/Fiona/microblog/app/__init__.py:25]
2018-07-15 23:02:00,797 INFO: Microblog startup [in /Users/Fiona/microblog/app/__init__.py:25]
2018-07-15 23:05:09,001 INFO: Microblog startup [in /Users/Fiona/microblog/app/__init__.py:25]
2018-07-15 23:06:01,972 INFO: Microblog startup [in /Users/Fiona/microblog/app/__init__.py:25]
2018-07-15 23:10:19,310 INFO: Microblog startup [in /Users/Fiona/microblog/app/__init__.py:25]
2018-07-15 23:12:18,960 INFO: Microblog startup [in /Users/Fiona/microblog/app/__init__.py:25]
2018-07-15 23:22:17,614 INFO: Microblog startup [in /Users/Fiona/microblog/app/__init__.py:25]
2018-07-15 23:42:47,251 INFO: Microblog startup [in /Users/Fiona/microblog/app/__init__.py:25]
